const Food = {
	APPLE: {
		foodPoints: 4, 
	},
	CAKE_SLICE: {
		foodPoints: 2, 
	},
	CAKE_WHOLE: {
		foodPoints: 14, 
	},
}

export default Food;

// Apple: 4,
// Baked Potato: 5,
// Beetroot: 1,
// Beetroot Soup: 6,
// Bread: 5,
// Cake (slice): 2,
// Cake (whole): 14,
// Carrot: 3,
// Chorus Fruit: 4,
// Clownfish: 1,
// Cooked Chicken: 6,
// Cooked Fish: 5,
// Cooked Mutton: 6,
// Cooked Porkchop: 8,
// Cooked Rabbit: 5,
// Cooked Salmon: 6,
// Cookie: 2,
// Enchanted Golden Apple: 4,
// Golden Apple: 4,
// Golden Carrot: 6,
// Melon: 2,
// Mushroom Stew: 6,
// Poisonous Potato: 2,
// Potato: 1,
// Pufferfish: 1,
// Pumpkin Pie: 8,
// Rabbit Stew: 10,
// Raw Beef: 3,
// Raw Chicken: 2,
// Raw Fish: 2,
// Raw Mutton: 2,
// Raw Porkchop: 3,
// Raw Rabbit: 3,
// Raw Salmon: 2,
// Rotten Flesh: 4,
// Spider Eye: 2,
// Steak: 8,